/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreditCardDemo: typeof import('./theme/components/vue-demo/CreditCardDemo.vue')['default']
    DateInputDemo: typeof import('./theme/components/vue-demo/DateInputDemo.vue')['default']
    Home: typeof import('./theme/components/Home.vue')['default']
    HomeContributors: typeof import('./theme/components/HomeContributors.vue')['default']
    HomeSponsors: typeof import('./theme/components/HomeSponsors.vue')['default']
    HomeTeam: typeof import('./theme/components/HomeTeam.vue')['default']
    NumeralInputDemo: typeof import('./theme/components/vue-demo/NumeralInputDemo.vue')['default']
    PhoneInputDemo: typeof import('./theme/components/vue-demo/PhoneInputDemo.vue')['default']
    TeamMember: typeof import('./theme/components/TeamMember.vue')['default']
    TimeInputDemo: typeof import('./theme/components/vue-demo/TimeInputDemo.vue')['default']
  }
}
